/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkImageInfo */

#ifndef _Included_com_caverock_skia4j_SkImageInfo
#define _Included_com_caverock_skia4j_SkImageInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caverock_skia4j_SkImageInfo
 * Method:    nSkImageInfoNew
 * Signature: (IIIIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkImageInfo_nSkImageInfoNew
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong);

/*
 * Class:     com_caverock_skia4j_SkImageInfo
 * Method:    nSkImageInfoDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkImageInfo_nSkImageInfoDelete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
