/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkPaint */

#ifndef _Included_com_caverock_skia4j_SkPaint
#define _Included_com_caverock_skia4j_SkPaint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintNew
  (JNIEnv *, jclass);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetAntialias
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetAntialias
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetBlendMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetBlendMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetColor
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetColor
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetDither
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetDither
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetFilterQuality
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetFilterQuality
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetStrokeWidth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetStrokeWidth
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetStrokeMiter
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetStrokeMiter
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetStrokeCap
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetStrokeCap
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetStrokeJoin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetStrokeJoin
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetStyle
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetStyle
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
