/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkPath */

#ifndef _Included_com_caverock_skia4j_SkPath
#define _Included_com_caverock_skia4j_SkPath
#ifdef __cplusplus
extern "C" {
#endif
#undef com_caverock_skia4j_SkPath_kLine_SegmentMask
#define com_caverock_skia4j_SkPath_kLine_SegmentMask 1L
#undef com_caverock_skia4j_SkPath_kQuad_SegmentMask
#define com_caverock_skia4j_SkPath_kQuad_SegmentMask 2L
#undef com_caverock_skia4j_SkPath_kConic_SegmentMask
#define com_caverock_skia4j_SkPath_kConic_SegmentMask 4L
#undef com_caverock_skia4j_SkPath_kCubic_SegmentMask
#define com_caverock_skia4j_SkPath_kCubic_SegmentMask 8L
/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkPath_nNew__
  (JNIEnv *, jclass);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nNew
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkPath_nNew__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nUnref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nUnref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nEquals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkPath_nEquals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nIsInterpolatable
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkPath_nIsInterpolatable
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nInterpolate
 * Signature: (JJFJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkPath_nInterpolate
  (JNIEnv *, jclass, jlong, jlong, jfloat, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nGetFillType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkPath_nGetFillType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nSetFillType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nSetFillType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nIsInverseFillType
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkPath_nIsInverseFillType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nToggleInverseFillType
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nToggleInverseFillType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nGetConvexity
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkPath_nGetConvexity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nSetConvexity
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nSetConvexity
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nIsConvex
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkPath_nIsConvex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nReset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nRewind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nRewind
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nIsEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkPath_nIsEmpty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nIsLastContourClosed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkPath_nIsLastContourClosed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nIsFinite
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkPath_nIsFinite
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nIsVolatile
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkPath_nIsVolatile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nSetIsVolatile
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nSetIsVolatile
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nCountPoints
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkPath_nCountPoints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nGetPoint
 * Signature: (JI[F)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nGetPoint
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nGetPoints
 * Signature: (J[FI)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkPath_nGetPoints
  (JNIEnv *, jclass, jlong, jfloatArray, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nCountVerbs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkPath_nCountVerbs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nGetVerbs
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkPath_nGetVerbs
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nSwap
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nSwap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nGetBounds
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nGetBounds
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nUpdateBoundsCache
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nUpdateBoundsCache
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nComputeTightBounds
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nComputeTightBounds
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nConservativelyContainsRect
 * Signature: (JFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkPath_nConservativelyContainsRect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nIncReserve
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nIncReserve
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nMoveTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nMoveTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nRMoveTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nRMoveTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nLineTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nLineTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nRLineTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nRLineTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nQuadTo
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nQuadTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nRQuadTo
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nRQuadTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nConicTo
 * Signature: (JFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nConicTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nRConicTo
 * Signature: (JFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nRConicTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nCubicTo
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nCubicTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nRCubicTo
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nRCubicTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nArcTo
 * Signature: (JFFFFFFZ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nArcTo__JFFFFFFZ
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nArcTo
 * Signature: (JFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nArcTo__JFFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nArcTo
 * Signature: (JFFFIIFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nArcTo__JFFFIIFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jint, jint, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nRArcTo
 * Signature: (JFFFIIFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nRArcTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jint, jint, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nAddRect
 * Signature: (JFFFFII)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nAddRect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nAddOval
 * Signature: (JFFFFII)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nAddOval
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nAddCircle
 * Signature: (JFFFI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nAddCircle
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nAddArc
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nAddArc
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nAddRoundRect
 * Signature: (JFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nAddRoundRect__JFFFFFFI
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nAddRoundRect
 * Signature: (JFFFF[FI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nAddRoundRect__JFFFF_3FI
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloatArray, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nAddPath
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nAddPath__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nAddPath
 * Signature: (JJFFI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nAddPath__JJFFI
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nAddPath
 * Signature: (JJFFFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nAddPath__JJFFFFFFFFFI
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nReverseAddPath
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nReverseAddPath
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nOffset
 * Signature: (JFFJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nOffset__JFFJ
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nOffset
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nOffset__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nTransform
 * Signature: (JFFFFFFFFFJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nTransform__JFFFFFFFFFJ
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nTransform
 * Signature: (JFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nTransform__JFFFFFFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nSetLastPt
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPath_nSetLastPt
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nGetSegmentMasks
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkPath_nGetSegmentMasks
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nContains
 * Signature: (JFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkPath_nContains
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nWriteToMemory
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkPath_nWriteToMemory
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nReadFromMemory
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkPath_nReadFromMemory
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_caverock_skia4j_SkPath
 * Method:    nGetGenerationID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkPath_nGetGenerationID
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
