/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkPaint */

#ifndef _Included_com_caverock_skia4j_SkPaint
#define _Included_com_caverock_skia4j_SkPaint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintNew
  (JNIEnv *, jclass);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetAntialias
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetAntialias
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_caverock_skia4j_SkPaint
 * Method:    nSkPaintSetColor
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkPaint_nSkPaintSetColor
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
