/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkData */

#ifndef _Included_com_caverock_skia4j_SkData
#define _Included_com_caverock_skia4j_SkData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caverock_skia4j_SkData
 * Method:    nSkMakeWithCopy
 * Signature: ([BII)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkData_nSkMakeWithCopy
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_caverock_skia4j_SkData
 * Method:    nSkMakeFromFileName
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkData_nSkMakeFromFileName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_caverock_skia4j_SkData
 * Method:    nSkDataRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkData_nSkDataRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkData
 * Method:    nSkDataUnref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkData_nSkDataUnref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkData
 * Method:    nSkDataGetSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkData_nSkDataGetSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkData
 * Method:    nSkDataToByteArray
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_caverock_skia4j_SkData_nSkDataToByteArray
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
