/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkIRect */

#ifndef _Included_com_caverock_skia4j_SkIRect
#define _Included_com_caverock_skia4j_SkIRect
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
