/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkImage */

#ifndef _Included_com_caverock_skia4j_SkImage
#define _Included_com_caverock_skia4j_SkImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caverock_skia4j_SkImage
 * Method:    nSkImageEncode
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkImage_nSkImageEncode
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_caverock_skia4j_SkImage
 * Method:    nSkMakeFromEncoded
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkImage_nSkMakeFromEncoded__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkImage
 * Method:    nSkMakeFromEncoded
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkImage_nSkMakeFromEncoded__JIIII
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_caverock_skia4j_SkImage
 * Method:    nSkImageRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkImage_nSkImageRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkImage
 * Method:    nSkImageUnref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkImage_nSkImageUnref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkImage
 * Method:    nSkImageGetWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkImage_nSkImageGetWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkImage
 * Method:    nSkImageGetHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkImage_nSkImageGetHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkImage
 * Method:    nSkImageGetAlphaType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkImage_nSkImageGetAlphaType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkImage
 * Method:    nSkImageGetColorSpace
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkImage_nSkImageGetColorSpace
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkImage
 * Method:    nSkImageGetUniqueId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkImage_nSkImageGetUniqueId
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
