/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkSurface */

#ifndef _Included_com_caverock_skia4j_SkSurface
#define _Included_com_caverock_skia4j_SkSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caverock_skia4j_SkSurface
 * Method:    nSkSurfaceMakeRaster
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkSurface_nSkSurfaceMakeRaster
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_caverock_skia4j_SkSurface
 * Method:    nSkSurfaceMakeRasterDirect
 * Signature: (J[BIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkSurface_nSkSurfaceMakeRasterDirect
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong);

/*
 * Class:     com_caverock_skia4j_SkSurface
 * Method:    nSkSurfaceUnref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkSurface_nSkSurfaceUnref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkSurface
 * Method:    nSkSurfaceGetCanvas
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkSurface_nSkSurfaceGetCanvas
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkSurface
 * Method:    nSkSurfaceMakeImageSnapshot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkSurface_nSkSurfaceMakeImageSnapshot
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
