/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkImageInfo_SkAlphaType */

#ifndef _Included_com_caverock_skia4j_SkImageInfo_SkAlphaType
#define _Included_com_caverock_skia4j_SkImageInfo_SkAlphaType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
