/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkCanvas */

#ifndef _Included_com_caverock_skia4j_SkCanvas
#define _Included_com_caverock_skia4j_SkCanvas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasSave
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasSave
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasSaveLayer
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasSaveLayer__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasSaveLayer
 * Signature: (JFFFFJ)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasSaveLayer__JFFFFJ
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasSaveLayerAlpha
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasSaveLayerAlpha__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasSaveLayerAlpha
 * Signature: (JFFFFI)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasSaveLayerAlpha__JFFFFI
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasGetSaveCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasGetSaveCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasRestore
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasRestore
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasRestoreToCount
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasRestoreToCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasTranslate
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasTranslate
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasScale
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasScale
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasRotate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasRotate__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasRotate
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasRotate__JFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasSkew
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasSkew
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasConcat
 * Signature: (JFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasConcat
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawPaint
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawPaint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawRect
 * Signature: (JFFFFJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawRect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawCircle
 * Signature: (JFFFJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawCircle
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawOval
 * Signature: (JFFFFJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawOval
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawArc
 * Signature: (JFFFFFFZJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawArc
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jboolean, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawLine
 * Signature: (JFFFFJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawLine
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawPoint
 * Signature: (JFFJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawPoint
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawPoints
 * Signature: (JII[FJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawPoints
  (JNIEnv *, jclass, jlong, jint, jint, jfloatArray, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawImage
 * Signature: (JJFFJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawImage
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jlong);

#ifdef __cplusplus
}
#endif
#endif
