/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkCanvas */

#ifndef _Included_com_caverock_skia4j_SkCanvas
#define _Included_com_caverock_skia4j_SkCanvas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawPaint
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawPaint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawRect
 * Signature: (JFFFFJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawRect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawCircle
 * Signature: (JFFFJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawCircle
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     com_caverock_skia4j_SkCanvas
 * Method:    nSkCanvasDrawOval
 * Signature: (JFFFFJ)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkCanvas_nSkCanvasDrawOval
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

#ifdef __cplusplus
}
#endif
#endif
