/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkBlendMode */

#ifndef _Included_com_caverock_skia4j_SkBlendMode
#define _Included_com_caverock_skia4j_SkBlendMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
