/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkColorSpace */

#ifndef _Included_com_caverock_skia4j_SkColorSpace
#define _Included_com_caverock_skia4j_SkColorSpace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caverock_skia4j_SkColorSpace
 * Method:    nSkColorSpaceMakeSRGB
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkColorSpace_nSkColorSpaceMakeSRGB
  (JNIEnv *, jclass);

/*
 * Class:     com_caverock_skia4j_SkColorSpace
 * Method:    nSkColorSpaceMakeSRGBLinear
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkColorSpace_nSkColorSpaceMakeSRGBLinear
  (JNIEnv *, jclass);

/*
 * Class:     com_caverock_skia4j_SkColorSpace
 * Method:    nSkColorSpaceUnref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_caverock_skia4j_SkColorSpace_nSkColorSpaceUnref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkColorSpace
 * Method:    nSkColorSpaceIsSRGB
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkColorSpace_nSkColorSpaceIsSRGB
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_caverock_skia4j_SkColorSpace
 * Method:    nSkColorSpaceGammaIsLinear
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_caverock_skia4j_SkColorSpace_nSkColorSpaceGammaIsLinear
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
