/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_SkColorSpace */

#ifndef _Included_com_caverock_skia4j_SkColorSpace
#define _Included_com_caverock_skia4j_SkColorSpace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caverock_skia4j_SkColorSpace
 * Method:    nColorSpaceNewSrgb
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_caverock_skia4j_SkColorSpace_nColorSpaceNewSrgb
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
