/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caverock_skia4j_Color */

#ifndef _Included_com_caverock_skia4j_Color
#define _Included_com_caverock_skia4j_Color
#ifdef __cplusplus
extern "C" {
#endif
#undef com_caverock_skia4j_Color_BLACK
#define com_caverock_skia4j_Color_BLACK -16777216L
#undef com_caverock_skia4j_Color_DKGRAY
#define com_caverock_skia4j_Color_DKGRAY -12303292L
#undef com_caverock_skia4j_Color_GRAY
#define com_caverock_skia4j_Color_GRAY -7829368L
#undef com_caverock_skia4j_Color_LTGRAY
#define com_caverock_skia4j_Color_LTGRAY -3355444L
#undef com_caverock_skia4j_Color_WHITE
#define com_caverock_skia4j_Color_WHITE -1L
#undef com_caverock_skia4j_Color_RED
#define com_caverock_skia4j_Color_RED -65536L
#undef com_caverock_skia4j_Color_GREEN
#define com_caverock_skia4j_Color_GREEN -16711936L
#undef com_caverock_skia4j_Color_BLUE
#define com_caverock_skia4j_Color_BLUE -16776961L
#undef com_caverock_skia4j_Color_YELLOW
#define com_caverock_skia4j_Color_YELLOW -256L
#undef com_caverock_skia4j_Color_CYAN
#define com_caverock_skia4j_Color_CYAN -16711681L
#undef com_caverock_skia4j_Color_MAGENTA
#define com_caverock_skia4j_Color_MAGENTA -65281L
#undef com_caverock_skia4j_Color_TRANSPARENT
#define com_caverock_skia4j_Color_TRANSPARENT 0L
#ifdef __cplusplus
}
#endif
#endif
